// Code generated by jetted for TypeScript v0.1.0

export enum EnumCollisionsFooBar {
  X = "x",
  Y = "y",
}

export interface EnumCollisionsFoo {
  bar: EnumCollisionsFooBar;
}

export enum EnumCollisionsFooBar0 {
  X = "x",
  Y = "y",
}

export interface EnumCollisions {
  foo: EnumCollisionsFoo;
  foo_bar: EnumCollisionsFooBar0;
}
