// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootFloat64JsonConverter))]
    public class RootFloat64
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public double Value { get; set; }
    }

    public class RootFloat64JsonConverter : JsonConverter<RootFloat64>
    {
        public override RootFloat64 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootFloat64 { Value = JsonSerializer.Deserialize<double>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootFloat64 value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<double>(writer, value.Value, options);
        }
    }
}
