// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class RootUint32 {
    @JsonValue
    private UnsignedInteger value;

    public RootUint32() {
    }

    @JsonCreator
    public RootUint32(UnsignedInteger value) {
        this.value = value;
    }

    public UnsignedInteger getValue() {
        return value;
    }

    public void setValue(UnsignedInteger value) {
        this.value = value;
    }
}
