// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum EnumCollisionsFooBar0 {
    @JsonProperty("x")
    X,

    @JsonProperty("y")
    Y,
}
