// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class EnumCollisions {
    @JsonProperty("foo")
    private EnumCollisionsFoo foo;

    @JsonProperty("foo_bar")
    private EnumCollisionsFooBar0 fooBar;

    public EnumCollisions() {
    }

    /**
     * Getter for foo.<p>
     */
    public EnumCollisionsFoo getFoo() {
        return foo;
    }

    /**
     * Setter for foo.<p>
     */
    public void setFoo(EnumCollisionsFoo foo) {
        this.foo = foo;
    }

    /**
     * Getter for fooBar.<p>
     */
    public EnumCollisionsFooBar0 getFooBar() {
        return fooBar;
    }

    /**
     * Setter for fooBar.<p>
     */
    public void setFooBar(EnumCollisionsFooBar0 fooBar) {
        this.fooBar = fooBar;
    }
}
