// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class EnumCollisionsFoo {
    @JsonProperty("bar")
    private EnumCollisionsFooBar bar;

    public EnumCollisionsFoo() {
    }

    /**
     * Getter for bar.<p>
     */
    public EnumCollisionsFooBar getBar() {
        return bar;
    }

    /**
     * Setter for bar.<p>
     */
    public void setBar(EnumCollisionsFooBar bar) {
        this.bar = bar;
    }
}
