// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type EmptyAndNonasciiDefinitions = string

type DefaultName = string

type Foo = string

type Foo0 = string

type Foo1 = string

type FooBar = string

type FooBar0 = string

type Foo0bar = string

type FooBar1 = string
