// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class EmptyAndNonasciiDefinitions {
    @JsonValue
    private String value;

    public EmptyAndNonasciiDefinitions() {
    }

    @JsonCreator
    public EmptyAndNonasciiDefinitions(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
