// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootTimestampJsonConverter))]
    public class RootTimestamp
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public DateTimeOffset Value { get; set; }
    }

    public class RootTimestampJsonConverter : JsonConverter<RootTimestamp>
    {
        public override RootTimestamp Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootTimestamp { Value = JsonSerializer.Deserialize<DateTimeOffset>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootTimestamp value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<DateTimeOffset>(writer, value.Value, options);
        }
    }
}
