// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

import (
	"encoding/json"
	"fmt"
)

type BasicDiscriminator struct {
	Foo string

	BarBaz BasicDiscriminatorBarBaz

	Quux BasicDiscriminatorQuux
}

func (v BasicDiscriminator) MarshalJSON() ([]byte, error) {
	switch v.Foo {
	case "BAR_BAZ":
		return json.Marshal(struct { T string `json:"foo"`; BasicDiscriminatorBarBaz }{ v.Foo, v.BarBaz })
	case "QUUX":
		return json.Marshal(struct { T string `json:"foo"`; BasicDiscriminatorQuux }{ v.Foo, v.Quux })
	}

	return nil, fmt.Errorf("bad Foo value: %s", v.Foo)
}

func (v *BasicDiscriminator) UnmarshalJSON(b []byte) error {
	var t struct { T string `json:"foo"` }
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}

	var err error
	switch t.T {
	case "BAR_BAZ":
		err = json.Unmarshal(b, &v.BarBaz)
	case "QUUX":
		err = json.Unmarshal(b, &v.Quux)
	default:
		err = fmt.Errorf("bad Foo value: %s", t.T)
	}

	if err != nil {
		return err
	}

	v.Foo = t.T
	return nil
}

type BasicDiscriminatorBarBaz struct {
	Baz string `json:"baz"`
}

type BasicDiscriminatorQuux struct {
	Quuz string `json:"quuz"`
}
