// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type Root struct {
	Bar []string `json:"bar,omitempty"`

	Baz *bool `json:"baz,omitempty"`

	Foo *string `json:"foo,omitempty"`
}
