// Code generated by jetted for TypeScript v0.1.0

export type DiscriminatorOptionalProperties = DiscriminatorOptionalPropertiesBar;

export interface DiscriminatorOptionalPropertiesBar {
  foo: "bar";
  baz?: string[];
  quux?: boolean;
}
