// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(NullableEnumJsonConverter))]
    public class NullableEnum
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public NullableEnum0? Value { get; set; }
    }

    public class NullableEnumJsonConverter : JsonConverter<NullableEnum>
    {
        public override NullableEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new NullableEnum { Value = JsonSerializer.Deserialize<NullableEnum0?>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, NullableEnum value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<NullableEnum0?>(writer, value.Value, options);
        }
    }
}
