// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(NullableEnum0JsonConverter))]
    public enum NullableEnum0
    {
        Bar,

        Baz,

        Foo,
    }
    public class NullableEnum0JsonConverter : JsonConverter<NullableEnum0>
    {
        public override NullableEnum0 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "Bar":
                    return NullableEnum0.Bar;
                case "Baz":
                    return NullableEnum0.Baz;
                case "Foo":
                    return NullableEnum0.Foo;
                default:
                    throw new ArgumentException(String.Format("Bad NullableEnum0 value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, NullableEnum0 value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case NullableEnum0.Bar:
                    JsonSerializer.Serialize<string>(writer, "Bar", options);
                    return;
                case NullableEnum0.Baz:
                    JsonSerializer.Serialize<string>(writer, "Baz", options);
                    return;
                case NullableEnum0.Foo:
                    JsonSerializer.Serialize<string>(writer, "Foo", options);
                    return;
            }
        }
    }
}
