// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BasicProperties {
    #[serde(rename = "bar")]
    pub bar: String,

    #[serde(rename = "baz")]
    pub baz: Vec<bool>,

    #[serde(rename = "foo")]
    pub foo: bool,

    #[serde(rename = "quux")]
    pub quux: Vec<bool>,
}
