// Code generated by jetted for TypeScript v0.1.0

export enum EmptyAndNonasciiEnumValues {
  DefaultName = "",
  Foo = "$foo",
  Foo0 = "0foo",
  Foo1 = "_foo",
  FooBar = "foo\nbar",
  FooBar0 = "foo bar",
  Foo0bar = "foo0bar",
  FooBar1 = "foo﷽bar",
}
