// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(tag = "foo")]
pub enum DiscriminatorOptionalProperties {
    #[serde(rename = "bar")]
    Bar(DiscriminatorOptionalPropertiesBar),
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DiscriminatorOptionalPropertiesBar {
    #[serde(rename = "baz")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub baz: Option<Box<Vec<String>>>,

    #[serde(rename = "quux")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quux: Option<Box<bool>>,
}
