// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum EnumVariantCollisions {
    @JsonProperty("FOO")
    FOO,

    @JsonProperty("Foo")
    FOO0,

    @JsonProperty("foo")
    FOO1,
}
