// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type EnumCollisionsFooBar string

const (
	EnumCollisionsFooBarX EnumCollisionsFooBar = "x"

	EnumCollisionsFooBarY EnumCollisionsFooBar = "y"
)

type EnumCollisionsFoo struct {
	Bar EnumCollisionsFooBar `json:"bar"`
}

type EnumCollisionsFooBar0 string

const (
	EnumCollisionsFooBarX0 EnumCollisionsFooBar0 = "x"

	EnumCollisionsFooBarY0 EnumCollisionsFooBar0 = "y"
)

type EnumCollisions struct {
	Foo EnumCollisionsFoo `json:"foo"`

	FooBar EnumCollisionsFooBar0 `json:"foo_bar"`
}
