// Code generated by jetted for Rust v0.2.0

use chrono::{DateTime, FixedOffset};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NullableTimestampProperty {
    #[serde(rename = "foo")]
    pub foo: Option<Box<DateTime<FixedOffset>>>,
}
