// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum EnumVariantCollisions {
    #[serde(rename = "FOO")]
    Foo,

    #[serde(rename = "Foo")]
    Foo0,

    #[serde(rename = "foo")]
    Foo1,
}
