// Code generated by jetted for Rust v0.1.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum EnumVariantCollisions {
    #[serde(rename = "FOO")]
    Foo,

    #[serde(rename = "Foo")]
    Foo0,

    #[serde(rename = "foo")]
    Foo1,
}
