// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootUint16JsonConverter))]
    public class RootUint16
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public ushort Value { get; set; }
    }

    public class RootUint16JsonConverter : JsonConverter<RootUint16>
    {
        public override RootUint16 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootUint16 { Value = JsonSerializer.Deserialize<ushort>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootUint16 value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<ushort>(writer, value.Value, options);
        }
    }
}
