// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootBooleanJsonConverter))]
    public class RootBoolean
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public bool Value { get; set; }
    }

    public class RootBooleanJsonConverter : JsonConverter<RootBoolean>
    {
        public override RootBoolean Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootBoolean { Value = JsonSerializer.Deserialize<bool>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootBoolean value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<bool>(writer, value.Value, options);
        }
    }
}
