// Code generated by jetted for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JettedE2E
{
    public class RootNestedIdInitialism
    {
        [JsonPropertyName("json")]
        public string Json { get; set; }

        [JsonPropertyName("normalword")]
        public string Normalword { get; set; }
    }
}
