// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type EmptyAndNonasciiEnumValues string

const (
	EmptyAndNonasciiEnumValues0 EmptyAndNonasciiEnumValues = ""

	EmptyAndNonasciiEnumValuesFoo EmptyAndNonasciiEnumValues = "$foo"

	EmptyAndNonasciiEnumValuesFoo0 EmptyAndNonasciiEnumValues = "0foo"

	EmptyAndNonasciiEnumValuesFoo1 EmptyAndNonasciiEnumValues = "_foo"

	EmptyAndNonasciiEnumValuesFooBar EmptyAndNonasciiEnumValues = "foo\nbar"

	EmptyAndNonasciiEnumValuesFooBar0 EmptyAndNonasciiEnumValues = "foo bar"

	EmptyAndNonasciiEnumValuesFoo0bar EmptyAndNonasciiEnumValues = "foo0bar"

	EmptyAndNonasciiEnumValuesFooBar1 EmptyAndNonasciiEnumValues = "foo﷽bar"
)
