// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type Root string

const (
	Root0 Root = ""

	RootFoo Root = "$foo"

	RootFoo0 Root = "0foo"

	RootFoo1 Root = "_foo"

	RootFooBar Root = "foo\nbar"

	RootFooBar0 Root = "foo bar"

	RootFoo0bar Root = "foo0bar"

	RootFooBar1 Root = "foo﷽bar"
)
