// Code generated by jetted for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JettedE2E
{
    public class EnumCollisions
    {
        [JsonPropertyName("foo")]
        public EnumCollisionsFoo Foo { get; set; }

        [JsonPropertyName("foo_bar")]
        public EnumCollisionsFooBar0 FooBar { get; set; }
    }
}
