// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(EnumCollisionsFooBarJsonConverter))]
    public enum EnumCollisionsFooBar
    {
        X,

        Y,
    }
    public class EnumCollisionsFooBarJsonConverter : JsonConverter<EnumCollisionsFooBar>
    {
        public override EnumCollisionsFooBar Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "x":
                    return EnumCollisionsFooBar.X;
                case "y":
                    return EnumCollisionsFooBar.Y;
                default:
                    throw new ArgumentException(String.Format("Bad EnumCollisionsFooBar value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EnumCollisionsFooBar value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EnumCollisionsFooBar.X:
                    JsonSerializer.Serialize<string>(writer, "x", options);
                    return;
                case EnumCollisionsFooBar.Y:
                    JsonSerializer.Serialize<string>(writer, "y", options);
                    return;
            }
        }
    }
}
