// Code generated by jetted for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JettedE2E
{
    public class EnumCollisionsFoo
    {
        [JsonPropertyName("bar")]
        public EnumCollisionsFooBar Bar { get; set; }
    }
}
