// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(EnumCollisionsFooBar0JsonConverter))]
    public enum EnumCollisionsFooBar0
    {
        X,

        Y,
    }
    public class EnumCollisionsFooBar0JsonConverter : JsonConverter<EnumCollisionsFooBar0>
    {
        public override EnumCollisionsFooBar0 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "x":
                    return EnumCollisionsFooBar0.X;
                case "y":
                    return EnumCollisionsFooBar0.Y;
                default:
                    throw new ArgumentException(String.Format("Bad EnumCollisionsFooBar0 value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, EnumCollisionsFooBar0 value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case EnumCollisionsFooBar0.X:
                    JsonSerializer.Serialize<string>(writer, "x", options);
                    return;
                case EnumCollisionsFooBar0.Y:
                    JsonSerializer.Serialize<string>(writer, "y", options);
                    return;
            }
        }
    }
}
