// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(EmptyAndNonasciiDefinitionsJsonConverter))]
    public class EmptyAndNonasciiDefinitions
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class EmptyAndNonasciiDefinitionsJsonConverter : JsonConverter<EmptyAndNonasciiDefinitions>
    {
        public override EmptyAndNonasciiDefinitions Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new EmptyAndNonasciiDefinitions { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, EmptyAndNonasciiDefinitions value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
