// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootInt8JsonConverter))]
    public class RootInt8
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public sbyte Value { get; set; }
    }

    public class RootInt8JsonConverter : JsonConverter<RootInt8>
    {
        public override RootInt8 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootInt8 { Value = JsonSerializer.Deserialize<sbyte>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootInt8 value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<sbyte>(writer, value.Value, options);
        }
    }
}
