// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type Root struct {
	Bar string `json:"bar"`

	Baz []bool `json:"baz"`

	Foo bool `json:"foo"`

	Quux []bool `json:"quux"`
}
