// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type NullableEnum0 string

const (
	NullableEnumBar NullableEnum0 = "Bar"

	NullableEnumBaz NullableEnum0 = "Baz"

	NullableEnumFoo NullableEnum0 = "Foo"
)

type NullableEnum = *NullableEnum0
