// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(DefinitionNameCollisionsJsonConverter))]
    public class DefinitionNameCollisions
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public Foo0 Value { get; set; }
    }

    public class DefinitionNameCollisionsJsonConverter : JsonConverter<DefinitionNameCollisions>
    {
        public override DefinitionNameCollisions Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new DefinitionNameCollisions { Value = JsonSerializer.Deserialize<Foo0>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, DefinitionNameCollisions value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<Foo0>(writer, value.Value, options);
        }
    }
}
