// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TypeCollisionsFooBar {
    #[serde(rename = "x")]
    pub x: bool,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TypeCollisionsFoo {
    #[serde(rename = "bar")]
    pub bar: TypeCollisionsFooBar,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TypeCollisionsFooBar0 {
    #[serde(rename = "x")]
    pub x: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TypeCollisions {
    #[serde(rename = "foo")]
    pub foo: TypeCollisionsFoo,

    #[serde(rename = "foo_bar")]
    pub foo_bar: TypeCollisionsFooBar0,
}
