// Code generated by jetted for TypeScript v0.1.0

export type BasicDiscriminator = BasicDiscriminatorBarBaz | BasicDiscriminatorQuux;

export interface BasicDiscriminatorBarBaz {
  foo: "BAR_BAZ";
  baz: string;
}

export interface BasicDiscriminatorQuux {
  foo: "QUUX";
  quuz: string;
}
