// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(ElementsJsonConverter))]
    public class Elements
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<string> Value { get; set; }
    }

    public class ElementsJsonConverter : JsonConverter<Elements>
    {
        public override Elements Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Elements { Value = JsonSerializer.Deserialize<IList<string>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Elements value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<string>>(writer, value.Value, options);
        }
    }
}
