// Code generated by jetted for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JettedE2E
{
    public class Root
    {
        [JsonPropertyName("for")]
        public For For { get; set; }

        [JsonPropertyName("object")]
        public Object_ Object_ { get; set; }
    }
}
