// Code generated by jetted for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JettedE2E
{
    public class BasicDiscriminatorQuux : BasicDiscriminator
    {
        [JsonPropertyName("foo")]
        public string Foo { get => "QUUX"; }

        [JsonPropertyName("quuz")]
        public string Quuz { get; set; }
    }
}
