// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(BasicDiscriminatorJsonConverter))]
    public abstract class BasicDiscriminator
    {
    }

    public class BasicDiscriminatorJsonConverter : JsonConverter<BasicDiscriminator>
    {
        public override BasicDiscriminator Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("foo").GetString();

            switch (tagValue)
            {
                case "BAR_BAZ":
                    return JsonSerializer.Deserialize<BasicDiscriminatorBarBaz>(ref readerCopy, options);
                case "QUUX":
                    return JsonSerializer.Deserialize<BasicDiscriminatorQuux>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad Foo value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, BasicDiscriminator value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
