// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A description for discriminator variant
 */
@JsonSerialize
public class DescriptionDiscriminatorWithDescriptionBar extends DescriptionDiscriminatorWithDescription {
    public DescriptionDiscriminatorWithDescriptionBar() {
    }
}
