// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type EnumVariantCollisions string

const (
	EnumVariantCollisionsFoo EnumVariantCollisions = "FOO"

	EnumVariantCollisionsFoo0 EnumVariantCollisions = "Foo"

	EnumVariantCollisionsFoo1 EnumVariantCollisions = "foo"
)
