// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootInt32JsonConverter))]
    public class RootInt32
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public int Value { get; set; }
    }

    public class RootInt32JsonConverter : JsonConverter<RootInt32>
    {
        public override RootInt32 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootInt32 { Value = JsonSerializer.Deserialize<int>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootInt32 value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<int>(writer, value.Value, options);
        }
    }
}
