// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct PropertyNameCollisions {
    #[serde(rename = "Foo")]
    pub foo: String,

    #[serde(rename = "foo")]
    pub foo0: String,
}
