# Code generated by jetted for Ruby v0.1.0

require 'json'
require 'time'

module JettedE2E

  class TypeCollisionsFooBar
    attr_accessor :x

    def self.from_json_data(data)
      out = TypeCollisionsFooBar.new
      out.x = JettedE2E::from_json_data(TrueClass, data["x"])
      out
    end

    def to_json_data
      data = {}
      data["x"] = JettedE2E::to_json_data(x)
      data
    end
  end

  class TypeCollisionsFoo
    attr_accessor :bar

    def self.from_json_data(data)
      out = TypeCollisionsFoo.new
      out.bar = JettedE2E::from_json_data(TypeCollisionsFooBar, data["bar"])
      out
    end

    def to_json_data
      data = {}
      data["bar"] = JettedE2E::to_json_data(bar)
      data
    end
  end

  class TypeCollisionsFooBar0
    attr_accessor :x

    def self.from_json_data(data)
      out = TypeCollisionsFooBar0.new
      out.x = JettedE2E::from_json_data(String, data["x"])
      out
    end

    def to_json_data
      data = {}
      data["x"] = JettedE2E::to_json_data(x)
      data
    end
  end

  class TypeCollisions
    attr_accessor :foo
    attr_accessor :foo_bar

    def self.from_json_data(data)
      out = TypeCollisions.new
      out.foo = JettedE2E::from_json_data(TypeCollisionsFoo, data["foo"])
      out.foo_bar = JettedE2E::from_json_data(TypeCollisionsFooBar0, data["foo_bar"])
      out
    end

    def to_json_data
      data = {}
      data["foo"] = JettedE2E::to_json_data(foo)
      data["foo_bar"] = JettedE2E::to_json_data(foo_bar)
      data
    end
  end

  private

  def self.from_json_data(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type == DateTime
      DateTime.rfc3339(data)
    elsif type.is_a?(Array)
      data.map { |elem| from_json_data(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json_data(type.values.first, elem) }
    else
      type.from_json_data(data)
    end
  end

  def self.to_json_data(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(DateTime)
      data.rfc3339
    elsif data.is_a?(Array)
      data.map { |elem| to_json_data(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json_data(elem) }
    else
      data.to_json_data
    end
  end
end
