// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(RootInt16JsonConverter))]
    public class RootInt16
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public short Value { get; set; }
    }

    public class RootInt16JsonConverter : JsonConverter<RootInt16>
    {
        public override RootInt16 Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new RootInt16 { Value = JsonSerializer.Deserialize<short>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, RootInt16 value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<short>(writer, value.Value, options);
        }
    }
}
