// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type TypeCollisionsFooBar struct {
	X bool `json:"x"`
}

type TypeCollisionsFoo struct {
	Bar TypeCollisionsFooBar `json:"bar"`
}

type TypeCollisionsFooBar0 struct {
	X string `json:"x"`
}

type TypeCollisions struct {
	Foo TypeCollisionsFoo `json:"foo"`

	FooBar TypeCollisionsFooBar0 `json:"foo_bar"`
}
