// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class RootUint8 {
    @JsonValue
    private UnsignedByte value;

    public RootUint8() {
    }

    @JsonCreator
    public RootUint8(UnsignedByte value) {
        this.value = value;
    }

    public UnsignedByte getValue() {
        return value;
    }

    public void setValue(UnsignedByte value) {
        this.value = value;
    }
}
