// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class RootInt16 {
    @JsonValue
    private Short value;

    public RootInt16() {
    }

    @JsonCreator
    public RootInt16(Short value) {
        this.value = value;
    }

    public Short getValue() {
        return value;
    }

    public void setValue(Short value) {
        this.value = value;
    }
}
