// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(BasicEnumJsonConverter))]
    public enum BasicEnum
    {
        Bar,

        Baz,

        Foo,
    }
    public class BasicEnumJsonConverter : JsonConverter<BasicEnum>
    {
        public override BasicEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "Bar":
                    return BasicEnum.Bar;
                case "Baz":
                    return BasicEnum.Baz;
                case "Foo":
                    return BasicEnum.Foo;
                default:
                    throw new ArgumentException(String.Format("Bad BasicEnum value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, BasicEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case BasicEnum.Bar:
                    JsonSerializer.Serialize<string>(writer, "Bar", options);
                    return;
                case BasicEnum.Baz:
                    JsonSerializer.Serialize<string>(writer, "Baz", options);
                    return;
                case BasicEnum.Foo:
                    JsonSerializer.Serialize<string>(writer, "Foo", options);
                    return;
            }
        }
    }
}
