// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum NullableEnum0 {
    #[serde(rename = "Bar")]
    Bar,

    #[serde(rename = "Baz")]
    Baz,

    #[serde(rename = "Foo")]
    Foo,
}

pub type NullableEnum = Option<Box<NullableEnum0>>;
