// Code generated by jetted for Rust v0.1.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "foo")]
pub enum BasicDiscriminator {
    #[serde(rename = "BAR_BAZ")]
    BarBaz(BasicDiscriminatorBarBaz),

    #[serde(rename = "QUUX")]
    Quux(BasicDiscriminatorQuux),
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BasicDiscriminatorBarBaz {
    #[serde(rename = "baz")]
    pub baz: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BasicDiscriminatorQuux {
    #[serde(rename = "quuz")]
    pub quuz: String,
}
