// Code generated by jetted for Rust v0.1.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct NullableProperties0 {
    #[serde(rename = "bar")]
    pub bar: String,

    #[serde(rename = "baz")]
    pub baz: Vec<bool>,

    #[serde(rename = "foo")]
    pub foo: bool,

    #[serde(rename = "quux")]
    pub quux: Vec<bool>,
}

pub type NullableProperties = Option<Box<NullableProperties0>>;
