// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "foo")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "bar", value = NullableDiscriminatorBar.class),
    @JsonSubTypes.Type(name = "quux", value = NullableDiscriminatorQuux.class),
})
public abstract class NullableDiscriminator {
}
