// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class CustomOverridesOverrideTypeDiscriminatorBaz extends Object {
    public CustomOverridesOverrideTypeDiscriminatorBaz() {
    }
}
