// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum CustomOverridesOverrideTypeEnum {
    @JsonProperty("BAR")
    BAR,

    @JsonProperty("FOO")
    FOO,
}
