// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class RootUint16 {
    @JsonValue
    private UnsignedShort value;

    public RootUint16() {
    }

    @JsonCreator
    public RootUint16(UnsignedShort value) {
        this.value = value;
    }

    public UnsignedShort getValue() {
        return value;
    }

    public void setValue(UnsignedShort value) {
        this.value = value;
    }
}
