// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;

public class RootTimestamp {
    @JsonValue
    private OffsetDateTime value;

    public RootTimestamp() {
    }

    @JsonCreator
    public RootTimestamp(OffsetDateTime value) {
        this.value = value;
    }

    public OffsetDateTime getValue() {
        return value;
    }

    public void setValue(OffsetDateTime value) {
        this.value = value;
    }
}
