// Code generated by jetted for TypeScript v0.1.0

export interface EmptyAndNonasciiProperties {
  "": string;
  $foo: string;
  "0foo": string;
  _foo: string;
  "foo\nbar": string;
  "foo bar": string;
  foo0bar: string;
  "foo﷽bar": string;
}
