// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type CustomOverridesOverrideTypeDiscriminatorBaz struct {
}

type CustomOverrides struct {
	OverrideElementsContainer []string `json:"override_elements_container"`

	OverrideTypeDiscriminator interface{} `json:"override_type_discriminator"`

	OverrideTypeEnum interface{} `json:"override_type_enum"`

	OverrideTypeExpr interface{} `json:"override_type_expr"`

	OverrideTypeProperties interface{} `json:"override_type_properties"`

	OverrideValuesContainer map[string]string `json:"override_values_container"`
}
