// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public class Reference {
    @JsonValue
    private Foo value;

    public Reference() {
    }

    @JsonCreator
    public Reference(Foo value) {
        this.value = value;
    }

    public Foo getValue() {
        return value;
    }

    public void setValue(Foo value) {
        this.value = value;
    }
}
