// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

import (
	"encoding/json"
	"fmt"
)

// A description for discriminator
type DescriptionDiscriminatorWithDescription struct {
	Foo string

	Bar DescriptionDiscriminatorWithDescriptionBar
}

func (v DescriptionDiscriminatorWithDescription) MarshalJSON() ([]byte, error) {
	switch v.Foo {
	case "bar":
		return json.Marshal(struct { T string `json:"foo"`; DescriptionDiscriminatorWithDescriptionBar }{ v.Foo, v.Bar })
	}

	return nil, fmt.Errorf("bad Foo value: %s", v.Foo)
}

func (v *DescriptionDiscriminatorWithDescription) UnmarshalJSON(b []byte) error {
	var t struct { T string `json:"foo"` }
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}

	var err error
	switch t.T {
	case "bar":
		err = json.Unmarshal(b, &v.Bar)
	default:
		err = fmt.Errorf("bad Foo value: %s", t.T)
	}

	if err != nil {
		return err
	}

	v.Foo = t.T
	return nil
}

// A description for discriminator variant
type DescriptionDiscriminatorWithDescriptionBar struct {
}

// A description for enum
type DescriptionEnumWithDescription string

const (
// A description for X
	DescriptionEnumWithDescriptionX DescriptionEnumWithDescription = "X"

// A description for Y
	DescriptionEnumWithDescriptionY DescriptionEnumWithDescription = "Y"

// A description for Z
	DescriptionEnumWithDescriptionZ DescriptionEnumWithDescription = "Z"
)

// A description for properties
type DescriptionPropertiesWithDescription struct {
}

type Description struct {
	// A description for discriminator
	DiscriminatorWithDescription DescriptionDiscriminatorWithDescription `json:"discriminator_with_description"`

	// A description for enum
	EnumWithDescription DescriptionEnumWithDescription `json:"enum_with_description"`

	// Whereas disregard and contempt for human rights have resulted in barbarous
	// acts which have outraged the conscience of mankind, and the advent of a
	// world in which human beings shall enjoy freedom of speech and belief and
	// freedom from fear and want has been proclaimed as the highest aspiration of
	// the common people,
	LongDescription string `json:"long_description"`

	// A description for properties
	PropertiesWithDescription DescriptionPropertiesWithDescription `json:"properties_with_description"`

	// A description for ref
	RefWithDescription Baz `json:"ref_with_description"`

	// A description for string
	StringWithDescription string `json:"string_with_description"`
}

// A description for a definition
type Baz = string
