// Code generated by jetted for Go v0.1.0. DO NOT EDIT.

package jetted_e2e

type BasicEnum string

const (
	BasicEnumBar BasicEnum = "Bar"

	BasicEnumBaz BasicEnum = "Baz"

	BasicEnumFoo BasicEnum = "Foo"
)
