// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    [JsonConverter(typeof(GeojsonJsonConverter))]
    public class Geojson
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public GeojsonObject Value { get; set; }
    }

    public class GeojsonJsonConverter : JsonConverter<Geojson>
    {
        public override Geojson Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Geojson { Value = JsonSerializer.Deserialize<GeojsonObject>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Geojson value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<GeojsonObject>(writer, value.Value, options);
        }
    }
}
