// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "foo")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "BAR_BAZ", value = BasicDiscriminatorBarBaz.class),
    @JsonSubTypes.Type(name = "QUUX", value = BasicDiscriminatorQuux.class),
})
public abstract class BasicDiscriminator {
}
