// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class BasicDiscriminatorBarBaz extends BasicDiscriminator {
    @JsonProperty("baz")
    private String baz;

    public BasicDiscriminatorBarBaz() {
    }

    /**
     * Getter for baz.<p>
     */
    public String getBaz() {
        return baz;
    }

    /**
     * Setter for baz.<p>
     */
    public void setBaz(String baz) {
        this.baz = baz;
    }
}
