// Code generated by jetted for Rust v0.1.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(tag = "foo")]
pub enum Root0 {
    #[serde(rename = "bar")]
    Bar(RootBar),

    #[serde(rename = "quux")]
    Quux(RootQuux),
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RootBar {
    #[serde(rename = "baz")]
    pub baz: String,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RootQuux {
    #[serde(rename = "quuz")]
    pub quuz: String,
}

pub type Root = Option<Box<Root0>>;
