// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[serde(tag = "foo")]
pub enum NullableDiscriminator0 {
    #[serde(rename = "bar")]
    Bar(NullableDiscriminatorBar),

    #[serde(rename = "quux")]
    Quux(NullableDiscriminatorQuux),
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NullableDiscriminatorBar {
    #[serde(rename = "baz")]
    pub baz: String,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NullableDiscriminatorQuux {
    #[serde(rename = "quuz")]
    pub quuz: String,
}

pub type NullableDiscriminator = Option<Box<NullableDiscriminator0>>;
