// Code generated by jetted for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JettedE2E
{
    /// <summary>
    /// A description for enum
    /// </summary>
    [JsonConverter(typeof(DescriptionEnumWithDescriptionJsonConverter))]
    public enum DescriptionEnumWithDescription
    {
        /// <summary>
        /// A description for X
        /// </summary>
        X,

        /// <summary>
        /// A description for Y
        /// </summary>
        Y,

        /// <summary>
        /// A description for Z
        /// </summary>
        Z,
    }
    public class DescriptionEnumWithDescriptionJsonConverter : JsonConverter<DescriptionEnumWithDescription>
    {
        public override DescriptionEnumWithDescription Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "X":
                    return DescriptionEnumWithDescription.X;
                case "Y":
                    return DescriptionEnumWithDescription.Y;
                case "Z":
                    return DescriptionEnumWithDescription.Z;
                default:
                    throw new ArgumentException(String.Format("Bad DescriptionEnumWithDescription value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, DescriptionEnumWithDescription value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case DescriptionEnumWithDescription.X:
                    JsonSerializer.Serialize<string>(writer, "X", options);
                    return;
                case DescriptionEnumWithDescription.Y:
                    JsonSerializer.Serialize<string>(writer, "Y", options);
                    return;
                case DescriptionEnumWithDescription.Z:
                    JsonSerializer.Serialize<string>(writer, "Z", options);
                    return;
            }
        }
    }
}
