// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class TypeCollisionsFooBar {
    @JsonProperty("x")
    private Boolean x;

    public TypeCollisionsFooBar() {
    }

    /**
     * Getter for x.<p>
     */
    public Boolean getX() {
        return x;
    }

    /**
     * Setter for x.<p>
     */
    public void setX(Boolean x) {
        this.x = x;
    }
}
