// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class TypeCollisionsFoo {
    @JsonProperty("bar")
    private TypeCollisionsFooBar bar;

    public TypeCollisionsFoo() {
    }

    /**
     * Getter for bar.<p>
     */
    public TypeCollisionsFooBar getBar() {
        return bar;
    }

    /**
     * Setter for bar.<p>
     */
    public void setBar(TypeCollisionsFooBar bar) {
        this.bar = bar;
    }
}
