// Code generated by jetted for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class TypeCollisions {
    @JsonProperty("foo")
    private TypeCollisionsFoo foo;

    @JsonProperty("foo_bar")
    private TypeCollisionsFooBar0 fooBar;

    public TypeCollisions() {
    }

    /**
     * Getter for foo.<p>
     */
    public TypeCollisionsFoo getFoo() {
        return foo;
    }

    /**
     * Setter for foo.<p>
     */
    public void setFoo(TypeCollisionsFoo foo) {
        this.foo = foo;
    }

    /**
     * Getter for fooBar.<p>
     */
    public TypeCollisionsFooBar0 getFooBar() {
        return fooBar;
    }

    /**
     * Setter for fooBar.<p>
     */
    public void setFooBar(TypeCollisionsFooBar0 fooBar) {
        this.fooBar = fooBar;
    }
}
