// Code generated by jetted for Rust v0.1.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Keywords {
    #[serde(rename = "for")]
    pub for_: For,

    #[serde(rename = "object")]
    pub object: Object,
}

pub type For = String;

pub type Object = String;
