// Code generated by jetted for Rust v0.2.0

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Keywords {
    #[serde(rename = "for")]
    pub for_: For,

    #[serde(rename = "object")]
    pub object: Object,
}

pub type For = String;

pub type Object = String;
