on:
  release:
    types: [published]

jobs:
  release_binary:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            runs_on: ubuntu-latest
            extension: ""
          - target: x86_64-unknown-linux-musl
            runs_on: ubuntu-latest
            extension: ""
          - target: x86_64-apple-darwin
            runs_on: macos-latest
            extension: ""
          - target: x86_64-pc-windows-gnu
            runs_on: ubuntu-latest
            extension: .exe
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add ${{ matrix.target }}
      - run: cargo install cross
      - name: Determine version
        run: echo "VERSION=${{ github.ref_name | replace('v', '') }}" >> $GITHUB_ENV
      - run: cross build --package jetted --release --target=${{ matrix.target }}
      - run: tar czf $TARGET.tar.gz target/$TARGET/release/jetted-$VERSION-${{ matrix.target }}${{ matrix.extension }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.target }}.tar.gz
          asset_name: ${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
