on:
  release:
    types: [published]

jobs:
  release_binary:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-gnu
            runs_on: ubuntu-latest
            extension: ""
          - target: x86_64-unknown-linux-musl
            runs_on: ubuntu-latest
            extension: ""
          - target: aarch64-unknown-linux-gnu
            runs_on: ubuntu-latest
            extension: ""
          - target: aarch64-unknown-linux-musl
            runs_on: ubuntu-latest
            extension: ""
          - target: x86_64-apple-darwin
            runs_on: macos-latest
            extension: ""
          - target: x86_64-pc-windows-gnu
            runs_on: ubuntu-latest
            extension: .exe
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add ${{ matrix.target }}
      - run: cargo install cross
      - name: Determine version
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION//v} # strip the 'v' prefix
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - run: echo "ARCHIVE=jetted-$VERSION-${{ matrix.target }}.tar.gz" >> $GITHUB_ENV
      - run: cross build --package jetted --release --target=${{ matrix.target }}
      - run: tar czf $ARCHIVE -C target/${{ matrix.target }}/release jetted${{ matrix.extension }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE }}
          asset_name: ${{ env.ARCHIVE }}
          asset_content_type: application/gzip
