on:
  release:
    types: [published]

jobs:
  release_binary:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            runs_on: ubuntu-latest
            artifact: jtd-codegen
          - target: x86_64-unknown-linux-musl
            runs_on: ubuntu-latest
            artifact: jtd-codegen
          - target: x86_64-apple-darwin
            runs_on: macos-latest
            artifact: jtd-codegen
          - target: x86_64-pc-windows-gnu
            runs_on: ubuntu-latest
            artifact: jtd-codegen.exe
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup target add ${{ matrix.target }}
      - run: cargo install cross
      - run: cross build --package jtd_codegen_cli --release --target=$TARGET
        env:
          TARGET: ${{ matrix.target }}
      - run: tar czf $TARGET.tar.gz target/$TARGET/release/$ARTIFACT
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.target }}.tar.gz
          asset_name: ${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
